/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data.structure;

import org.w3c.dom.Node;

public class App {

    public static void main(String[] args) {
        LinkedList ll = new LinkedList();
        ll.head = new LinkedList.Node(1);
        LinkedList.Node node1 = new LinkedList.Node(2);
        LinkedList.Node node2 = new LinkedList.Node(3);
        LinkedList.Node node3 = new LinkedList.Node(4);

        ll.head.next=node1;
        node1.next = node2;
        node2.next = node3;

        System.out.println(ll.toString());
        ll.insertAtStart(0);
        System.out.println(ll.toString());
        System.out.println(ll.includes(10));
    }

}
