/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.*;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public int[] roll(int n) {
        int arr[] = new int[n];
        for (int i = 0; i < n; i++) {
            arr[i]=(int)(Math.random()*5)+1;
        }
        return arr;
    }
    public boolean containsDuplicates(int arr[]) {
        HashSet<Integer> uniqeSet=new HashSet<Integer>();
        for (int i : arr) {
                if (uniqeSet.contains(i))
                    return true;
                uniqeSet.add(i);
        }
        return false;
    }

    public double average(int arr[]) {
        int sum=0;
        for(int i:arr)
            sum+=i;
       return (double) sum/arr.length;
    }
    public int[] lowestAverageArray(int arr[][]) {
        int lowestAvgIndex=0;
        double sum=0;
        double lastAvg=0;
        for (int i =0 ; i<arr.length;i++) {
            for (int j = 0; j < arr[i].length; j++) {
                sum += arr[i][j];
            }
            double avg = sum / arr[i].length;
            if (i == 0 || avg < lastAvg) {
                lastAvg = avg;
                lowestAvgIndex = i;
            }
            sum=0;
        }
        return arr[lowestAvgIndex];
    }

    public void minMaxTemp(int weeklyMonthTemperatures[][]) {
        HashSet<Integer> uniqueSet = new HashSet<>();
        for (int[] weeklyTemp : weeklyMonthTemperatures) {
            for (int temp : weeklyTemp) {
                uniqueSet.add(temp);
            }
        }

        Integer [] uniqueArr = uniqueSet.toArray(new Integer[uniqueSet.size()]);  //set.toArray() return Object
        Arrays.sort(uniqueArr); //I need to convert tht hashset to arraylist or array due to sorting
        int min =uniqueArr[0];
        int max = uniqueArr[uniqueArr.length-1];
        System.out.println("High: "+Collections.max(uniqueSet));
        System.out.println("Low: "+Collections.min(uniqueSet));
        for(int i= min+1;i<max;i++) {
            if(!uniqueSet.contains(i))
                System.out.println("never saw tempreture:"+i);
        }
    }
    public  String tally(List<String> votes) {
        HashMap<String, Integer> map = new HashMap<>();
        for (String vote : votes) {
            map.compute(vote, (key, value) -> (value == null) ? 1 : value + 1);
        }
        int maxValue = Collections.max(map.values());
        for (Map.Entry<String, Integer> entry : map.entrySet()) {
            if (entry.getValue() == maxValue) {
                return entry.getKey();
            }
        }
        return null;
    }


}
