/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        String path=  "./linter/app/src/main/resources/gates.txt";
fileReader(path);
    }
    public static ArrayList<Integer> fileReader(String path) {
        ArrayList<Integer> result = null;    // I will use it to test the result
        try {
            result = new ArrayList<>();
            Path filePath =Path.of(path);
            Scanner reader = new Scanner(filePath);
            int lineNumber=0;
            while (reader.hasNextLine()){
                lineNumber++;
            String line = reader.nextLine();
            if(line.isEmpty()||line.endsWith("{")||line.endsWith("}")||line.endsWith("if")||line.endsWith("else")||line.endsWith(";"))
                    continue;
                System.out.println("this line "+lineNumber+ ": does not end with semicolon");
                result.add(lineNumber);
            }
            reader.close();
        }catch (IOException e) {
            e.printStackTrace();
        }
        return result;
    }

}
