/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void  restaurantConstructor(){
        Restaurant res = new Restaurant("PizzaHut",5,15);
        String actualResult= res.toString();
        String expectedResult = "Restaurant{" +
                "Name='" + "PizzaHut" + '\'' +
                ", stars=" + 5 +
                ", price=" + 15 +
                '}';
        Assertions.assertEquals(expectedResult,actualResult);
    }
    @Test void reviewConstructor () {
        Restaurant res = new Restaurant("Burgurize",4,15);
        Review rev = new Review("nice restaurant","saif",5,res);
        String result ="Review{" +
                "body='" + "nice restaurant" + '\'' +
                ", author='" + "saif" + '\'' +
                ", stars=" + 5 +
                ", restaurant=" + res +
                '}';
        Assertions.assertEquals(result,rev.toString());
    }
    @Test void addReview () {
        Restaurant res = new Restaurant("PizzaHut",4,15);
        Review rev = new Review("nice restaurant","saif",5,res);
        res.addReview(rev);
        String result ="Restaurant{" +
                "Name='" + "PizzaHut" + '\'' +
                ", stars=" + 5 +
                ", price=" + 15 +
                '}';
        Assertions.assertEquals(result,res.toString());
    }
    @Test void addReviewRepeated () {
        Restaurant res = new Restaurant("PizzaHut",4,15);
        Review rev = new Review("nice restaurant","saif",5,res);
        Review newRev = new Review("bad restaurant","saif",3,res);
        res.addReview(rev);
        res.addReview(newRev); // here is the test must not take this review (stars won't be updated)
        String result ="Restaurant{" +
                "Name='" + "PizzaHut" + '\'' +
                ", stars=" + 3 +
                ", price=" + 15 +
                '}';
        Assertions.assertNotEquals(result,res.toString());
    }
}
